# Generated by Django 3.2.12 on 2022-03-11 19:59

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=300, null=True)),
                ('heading2', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300000, null=True)),
                ('image', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='blog_image/%Y/%m/%D/')),
            ],
        ),
        migrations.CreateModel(
            name='html',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=300000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300, null=True)),
                ('user_id', models.CharField(max_length=300, null=True)),
                ('full_name', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(max_length=300, null=True)),
                ('company_name', models.CharField(max_length=300, null=True)),
                ('company_type', models.CharField(max_length=300, null=True)),
                ('gst_number', models.CharField(max_length=300, null=True)),
                ('company_addess', models.CharField(max_length=3000, null=True)),
                ('p_number', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=300, null=True)),
                ('total_states', models.CharField(max_length=300, null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('payment', models.CharField(default='Unpaid', max_length=300, null=True)),
                ('pan_card', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='pan_card/%Y/%m/%D/')),
                ('proof_of_address', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='proof_of_address/%Y/%m/%D/')),
                ('photograph', models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='photograph/%Y/%m/%D/')),
                ('aadhar_card', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='aadhar_card/%Y/%m/%D/')),
                ('order_status', models.CharField(default='Unfulfilled', max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('pan_card1', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='pan_card/%Y/%m/%D/')),
            ],
        ),
        migrations.CreateModel(
            name='phone_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_price', models.CharField(max_length=300, null=True)),
                ('percentage', models.CharField(max_length=300, null=True)),
                ('percentage_price', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=300, null=True)),
                ('state_id', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
