# Generated by Django 3.2.12 on 2022-03-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_app', '0003_auto_20220313_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='price',
            name='percentage_price',
        ),
        migrations.AddField(
            model_name='price',
            name='price_with_percentage',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
