# Generated by Django 3.2.12 on 2022-03-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst_app', '0005_auto_20220315_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='payment',
        ),
    ]
