# Generated by Django 3.2.12 on 2022-03-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst_app', '0006_auto_20220316_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='aadhar_card',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='photograph',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='proof_of_address',
        ),
    ]
