# Generated by Django 3.2.12 on 2022-03-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_app', '0007_auto_20220316_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(default='Unpaid', max_length=300, null=True),
        ),
    ]
