# Generated by Django 3.2.12 on 2022-05-06 08:15

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('gst_app', '0008_orders_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='documents',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='heading2',
        ),
        migrations.AddField(
            model_name='orders',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='aadhar_card/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='orders',
            name='documents_uploaded',
            field=models.CharField(default='no', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='pan_card',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='pan_card/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='orders',
            name='photograph',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='photograph/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='orders',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='proof_of_address/%Y/%m/%D/'),
        ),
    ]
