# Generated by Django 3.2.12 on 2022-05-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst_app', '0009_auto_20220506_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='html',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='documents_uploaded',
        ),
    ]
